

client : client.c
	gcc -o client client.c -L.. -lshmsock-client -I.. -I../linked-list/include -I../custom-malloc -static -g


server : server.c
	gcc -o server server.c -L.. -lshmsock-server -I.. -I../linked-list/include -I../custom-malloc -static -g
